package com.udea.prestamodispositivos.dto;
// Generated 29-abr-2017 18:32:17 by Hibernate Tools 4.3.1



/**
 * DevicesId generated by hbm2java
 */
public class DevicesId  implements java.io.Serializable {


     private String code;
     private String copy;

    public DevicesId() {
    }

    public DevicesId(String code, String copy) {
       this.code = code;
       this.copy = copy;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getCopy() {
        return this.copy;
    }
    
    public void setCopy(String copy) {
        this.copy = copy;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DevicesId) ) return false;
		 DevicesId castOther = ( DevicesId ) other; 
         
		 return ( (this.getCode()==castOther.getCode()) || ( this.getCode()!=null && castOther.getCode()!=null && this.getCode().equals(castOther.getCode()) ) )
 && ( (this.getCopy()==castOther.getCopy()) || ( this.getCopy()!=null && castOther.getCopy()!=null && this.getCopy().equals(castOther.getCopy()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCode() == null ? 0 : this.getCode().hashCode() );
         result = 37 * result + ( getCopy() == null ? 0 : this.getCopy().hashCode() );
         return result;
   }   


}


