package com.udea.prestamodispositivos.dto;
// Generated 29-abr-2017 18:32:17 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LoansId generated by hbm2java
 */
public class LoansId  implements java.io.Serializable {


     private Date startDate;
     private String username;
     private String code;
     private String copy;

    public LoansId() {
    }

    public LoansId(Date startDate, String username, String code, String copy) {
       this.startDate = startDate;
       this.username = username;
       this.code = code;
       this.copy = copy;
    }
   
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getCopy() {
        return this.copy;
    }
    
    public void setCopy(String copy) {
        this.copy = copy;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LoansId) ) return false;
		 LoansId castOther = ( LoansId ) other; 
         
		 return ( (this.getStartDate()==castOther.getStartDate()) || ( this.getStartDate()!=null && castOther.getStartDate()!=null && this.getStartDate().equals(castOther.getStartDate()) ) )
 && ( (this.getUsername()==castOther.getUsername()) || ( this.getUsername()!=null && castOther.getUsername()!=null && this.getUsername().equals(castOther.getUsername()) ) )
 && ( (this.getCode()==castOther.getCode()) || ( this.getCode()!=null && castOther.getCode()!=null && this.getCode().equals(castOther.getCode()) ) )
 && ( (this.getCopy()==castOther.getCopy()) || ( this.getCopy()!=null && castOther.getCopy()!=null && this.getCopy().equals(castOther.getCopy()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getStartDate() == null ? 0 : this.getStartDate().hashCode() );
         result = 37 * result + ( getUsername() == null ? 0 : this.getUsername().hashCode() );
         result = 37 * result + ( getCode() == null ? 0 : this.getCode().hashCode() );
         result = 37 * result + ( getCopy() == null ? 0 : this.getCopy().hashCode() );
         return result;
   }   


}


