package com.udea.prestamos.model;
// Generated 30-abr-2017 2:26:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Devices generated by hbm2java
 */
public class Devices  implements java.io.Serializable {


     private DevicesId id;
     private String name;
     private String type;
     private String status;
     private String details;
     private Set loanses = new HashSet(0);

    public Devices() {
    }

	
    public Devices(DevicesId id, String name, String type, String status) {
        this.id = id;
        this.name = name;
        this.type = type;
        this.status = status;
    }
    public Devices(DevicesId id, String name, String type, String status, String details, Set loanses) {
       this.id = id;
       this.name = name;
       this.type = type;
       this.status = status;
       this.details = details;
       this.loanses = loanses;
    }
   
    public DevicesId getId() {
        return this.id;
    }
    
    public void setId(DevicesId id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }
    public Set getLoanses() {
        return this.loanses;
    }
    
    public void setLoanses(Set loanses) {
        this.loanses = loanses;
    }




}


