package com.udea.prestamos.model;
// Generated 30-abr-2017 2:26:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Users generated by hbm2java
 */
@XmlRootElement
public class Users  implements java.io.Serializable {


     private String username;
     private Users users;
     private String typeId;
     private String numberId;
     private String name;
     private String lastName;
     private String email;
     private String password;
     private String role;
     private Set loanses = new HashSet(0);
     private Set userses = new HashSet(0);

    public Users() {
    }

	
    public Users(String username, String typeId, String numberId, String name, String password, String role) {
        this.username = username;
        this.typeId = typeId;
        this.numberId = numberId;
        this.name = name;
        this.password = password;
        this.role = role;
    }
    public Users(String username, Users users, String typeId, String numberId, String name, String lastName, String email, String password, String role) {
       this.username = username;
       this.users = users;
       this.typeId = typeId;
       this.numberId = numberId;
       this.name = name;
       this.lastName = lastName;
       this.email = email;
       this.password = password;
       this.role = role;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }
    public String getNumberId() {
        return this.numberId;
    }
    
    public void setNumberId(String numberId) {
        this.numberId = numberId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public Set getLoanses() {
        return this.loanses;
    }
    
    public void setLoanses(Set loanses) {
        this.loanses = loanses;
    }
    public Set getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set userses) {
        this.userses = userses;
    }




}


